import{S as C,i,a as E}from"./assets/vendor-D5Cmjq_w.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&t(m)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function t(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();const v=document.querySelector(".form"),p=document.querySelector(".searchInput");document.querySelector(".searchButton");const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),S=document.querySelector(".load-more-container"),n=document.querySelector(".load-more-btn"),y=document.querySelector(".load-more-loader"),O="51442110-4fde2839a6cf4cc45b6823f02",x="https://pixabay.com/api/";let c=1;const b=40;let g=0,h="",B=new C(".gallery a.gallery-link",{navText:["❮","❯"],captionsData:"alt",captionDelay:250,captionPosition:"bottom",close:!0,closeText:"×",animationSlide:!0,animationSpeed:250,enableKeyboard:!0,overlay:!0,overlayOpacity:.8,sourceAttr:"href",zoom:!1});function l(o){o.classList.add("is-hidden")}function d(o){o.classList.remove("is-hidden")}function w(o){return o.map(e=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
            </a>
            <div class="image-info">
                <p class="info"><b>Likes</b>${e.likes}</p>
                <p class="info"><b>Views</b>${e.views}</p>
                <p class="info"><b>Comments</b>${e.comments}</p>
                <p class="info"><b>Downloads</b>${e.downloads}</p>
            </div>
        </li>`).join("")}async function L(o,e){const s=new URLSearchParams({key:O,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:b});try{return(await E.get(`${x}?${s}`)).data}catch(t){throw console.error("Error fetching images:",t),i.error({title:"Error",message:`An error occurred while fetching images: ${t.message}`,position:"topRight"}),t}}v.addEventListener("submit",async o=>{o.preventDefault();const e=p.value.trim();if(e===""){i.error({message:"Please enter a search term.",position:"topRight",backgroundColor:"#EF4040",messageColor:"white",progressBarColor:"#B51B1B",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"});return}c=1,h=e,u.innerHTML="",l(n),d(f);try{const s=await L(h,c);g=s.totalHits;const t=s.hits;if(t.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"white",progressBarColor:"#B51B1B",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"});return}u.innerHTML=w(t),B.refresh(),Math.ceil(g/b)>1?(d(n),S.classList.remove("is-hidden")):i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#3A8EBA",messageColor:"white",progressBarColor:"#1B5BB5",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"})}catch(s){i.error({title:"Error",message:`An error occurred while fetching images: ${s.message}`,position:"topRight"}),console.error("Error fetching images:",s)}finally{l(f),p.value=""}});n.addEventListener("click",async()=>{c+=1,l(n),d(y);try{const e=(await L(h,c)).hits,s=w(e);u.insertAdjacentHTML("beforeend",s),B.refresh();const t=u.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),c*40>=g?(l(n),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#3A8EBA",messageColor:"white",progressBarColor:"#1B5BB5",closeOnClick:!0,closeOnEscape:!0,close:!0,timeout:3e3,maxWidth:"450px"})):d(n)}catch(o){i.error({title:"Error",message:`An error occurred while fetching more images: ${o.message}`,position:"topRight"}),console.error("Error fetching more images:",o)}finally{l(y)}});
//# sourceMappingURL=index.js.map
